name: llmaava
channels:
  - conda-forge
dependencies:
  - flask
  - flask-cors
  - langchain
  - langchain-ollama
  - langchain-openai
  - pandas
  - psycopg
  - pydantic
  - pypika
  - python=3.13
  - python-dotenv
